apiVersion: v1
kind: ConfigMap
metadata:
  name: go-otel-sample-config
  namespace: go-otel-sample
  labels:
    app.kubernetes.io/name: go-otel-sample
data:
  SERVER_PORT: "8080"
  OTEL_SERVICE_NAME: "go-otel-sample"
  ENVIRONMENT: "development"
  # OTel Collector endpoint within the cluster
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector.go-otel-sample.svc.cluster.local:4317"
