apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-otel-sample

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: go-otel-sample
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
